[Configuration]
Port = COM5          # Alternative: /dev/ttyUSB0 oder /dev/serial/by-id/usb-IMST_iU891A_IMS3015-if00

# none | daily | monthly
SnapshotMode = daily

# Verzeichnis für JSON-Snapshots
#SnapshotDir = snapshots
SnapshotDir = tests/snapshots

# JSON-Datei mit Benutzerdaten
Userfile =  users.json

# JSON-Datei mit Zählerplätzen, Zählernummern und AES-Schlüsseln
Locationfile =  locations.json.enc

# Socket-Port, über den das Programm das Passwort annimmt
KeyPortMain  = 53165
KeyPortWmbus = 53166

# Liste mit Telegrammen, die ignoriert werden sollen (optional)
Blocklistfile = wmbusBlocklist.json
