[Configuration]
# Port des iU891A-XL-Empfängers
Port = auto  # Alternative: COM5 oder /dev/ttyUSB0 oder /dev/serial/by-id/usb-IMST_iU891A_IMS3015-if00

# none | daily | monthly | monthly_safe (daily: täglich um 23 Uhr, monthly: am Monatsletzten, monthly_safe: in den letzten 5 Tagen eines Monats um 23 Uhr)
SnapshotMode = daily

# Verzeichnis für JSON-Snapshots
#SnapshotDir = snapshots
SnapshotDir = tests/snapshots

# JSON-Datei mit Benutzerdaten
Userfile =  users.json

# JSON-Datei mit Zählerplätzen, Zählernummern und AES-Schlüsseln
Locationfile =  locations.json.enc

# Socket-Port, über den das Programm das Passwort annimmt
KeyPortMain  = 53165
KeyPortWmbus = 53166

# Liste mit Telegrammen, die ignoriert werden sollen (optional)
Blocklistfile = wmbusBlocklist.json

# Backup-Verzeichnis für Snapshots (optional, absoluter Pfad)
#BackupDir = /media/sf/0030-622B   # oder F:\
